kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: cadvisor
    category: rbac
    # WORKIVA CHANGE: disable cadvisor
    # deploy: sourcegraph
    sourcegraph-resource-requires: cluster-admin
    app.kubernetes.io/component: cadvisor
  name: cadvisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cadvisor
subjects:
- kind: ServiceAccount
  name: cadvisor
  # value of namespace needs to match namespace value in base/cadvisor/cadvisor.ServiceAccount.yaml
  namespace: default
