apiVersion: v1
imagePullSecrets:
- name: drydockcreds
kind: ServiceAccount
metadata:
  labels:
    app: cadvisor
    category: rbac
    deploy: sourcegraph
    sourcegraph-resource-requires: cluster-admin
    app.kubernetes.io/component: cadvisor
  name: cadvisor
